# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae8836e30169b29a1277249b8310f6f74ff26e55840a0dac8864899e89a5d2cb363a4fee8b21fb45c72447ec2a2d0066623d43ebce745be16645478018597e12

test:
  secret_key_base: 764bb22afaf3f765a0f3114f85221eac0e2ed7678c92c34ca7792ddfe136022d3fdecb7b353252fd08ff148c03a3e4b30e2c7f7e809502d5c68a1bacea9244a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
